### ISSUE TITLE
The RPM of the ring in the editor is inconsistent at high levels of damage

### ISSUE THREAD

**Issue by AeveanLeeow** [treeform/istrolid-bugs#12] opened 2017-07-10 02:57 UTC
The behavior is that the ring spins faster with more damage. However, at certain amounts of the damage the ring will spin much more slowly. This was tested by adding damage mods to a single ring.

The following ring damage values will experience RPM decreases in comparison to speeds demonstrated by earlier amounts of damage.

24706.5
19005
3028.8
6654.2

There are probably more damage values that experience slowdown if you modshare, allowing for different damage values than a single ring with damage mods.

**Comment by AeveanLeeow** [comment] 2017-07-17 19:55
literally unplayable tbh

**Comment by RyMarq** [comment] 2017-08-02 01:53
Helicopter Effect. Spins so fast its backwards. At least this games version of it.

At least that is the best I can determine as cause.

**Comment by q-rtz** [comment] 2017-09-06 01:29
I looked through the code and the ring turn per tick is basically just (ring damage * constant). That means that the slowing effect would probably be caused by the ring turning more than one revolution in a tick.

**Comment by treeform** [comment] 2017-09-30 15:34
Yeah its the thing. Closing.

**Closed as completed by treeform** 2017-09-30 15:34 UTC
Labels: enhancement
