### ISSUE TITLE
When the host changes the server type, it still says the original server type for me.

### ISSUE THREAD

**Issue by Jwdegames** [treeform/istrolid-bugs#33] opened 2017-10-19 23:45 UTC
I have to rejoin the server in order to get the updated game mode. Several others also have this issue.

**Comment by treeform** [comment] 2017-11-25 19:46
Can't reproduce. Some time ago root server would send you the info about the battle. But that is not the case any more. The game server itself sends you this info which should be more reliable. Do you still get this bug?

**Comment by astral-carrier** [comment] 2017-11-25 20:01
I do and will send you a screenshot when I see it again.

**Comment by treeform** [comment] 2018-07-22 00:39
I have found some issue with this and have a new fix out. 

Fixed in v48.0

Let me know if there are still issues after this release.

**Closed as completed by treeform** 2018-07-22 00:39 UTC
