### ISSUE TITLE
Client bugs sometimes when switching server type

### ISSUE THREAD

**Issue by astral-carrier** [treeform/istrolid-bugs#45] opened 2018-01-04 19:49 UTC
Here is a 3v3 after the server type was switched from 1v1t. Note the server type indicator says it is 3v3, and the chat shows the server has been changed to 3v3. Note, however, that the button above alpha team still says "Waiting for players 1v1t", and that the join button disappeared after only one person joined beta team, probably because it still appeared as 1v1t. Note also that 2 people were able to join alpha, which shows that the problem did not apply to all the players. 

![server switch bug](https://user-images.githubusercontent.com/32406395/34581175-66085310-f144-11e7-9ff4-fd91cab9cea6.PNG) 

@treeform here is the screenshot for the bug JWDEGames was talking about.

**Comment by lectrician1** [comment] 2018-01-05 01:35
Same bug as #33

**Comment by astral-carrier** [comment] 2018-01-05 01:36
@lectrician1 yes, but on that thread tree said he'd never seen it before, so here's a screenshot

**Comment by lectrician1** [comment] 2018-01-05 01:41
Then post the screenshot in that thread

**Comment by lectrician1** [comment] 2018-02-18 19:39
Please fix.

**Comment by treeform** [comment] 2018-07-21 23:56
Duplicate of #33

**Closed as completed by treeform** 2018-07-21 23:56 UTC

**Comment by astral-carrier** [comment] 2018-07-22 00:23
aaaAaAAAAAAAAaAAAAAAAAAaaAAAAAAAAa at long last the devs have replied!11!1!!!!!!1!1!
